name: Deploy Test

on:
  workflow_dispatch:
    inputs:
  push:
    branches:
    - develop

jobs:
  build-and-distribute:
    name: Build and distribute target
    runs-on: macOS-11
    timeout-minutes: 15
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Decrypt Secret Files
      run: ./.secret/decrypt.sh
      env:
        CERTIFICATE_PASSWORD: ${{ secrets.SECRETS_PASSWORD }}
    - name: Prepare to Deploy eduID App
      run: |
        bundle config set path 'vendor/bundle'
        bundle install
        bundle exec fastlane ios set_build_number
      env:
        CERTIFICATE_PASSWORD: ${{ secrets.SECRETS_PASSWORD }}
    - name: Deploy eduID Test App
      run: bundle exec fastlane ios deploy_test_ci --env test
      env:
        CERTIFICATE_PASSWORD: ${{ secrets.SECRETS_PASSWORD }}
        FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
